# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/master/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

import filecmp
import os
from pathlib import Path
import shutil
import sys
import tempfile

import kiwipy

# -- Project information -----------------------------------------------------

project = 'kiwiPy'
copyright = '2020, Martin Uhrin'
author = 'Martin Uhrin'

# The short X.Y version.
version = '.'.join(kiwipy.__version__.split('.')[:2])
# The full version, including alpha/beta/rc tags.
release = kiwipy.__version__

# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.viewcode',
    'nbsphinx',
]

intersphinx_mapping = {
    'python': ('https://docs.python.org/3.8', None),
    'aio_pika': ('https://docs.aio-pika.com/', None)
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'alabaster'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}
html_theme_options = {
    'analytics_id': 'UA-17296547-4',
    'codecov_button': True,
    'description': 'Robust, high-volume, message based communication made easy',
    'github_button': True,
    'github_repo': 'kiwipy',
    'github_type': 'star',
    'github_user': 'aiidateam',
    'logo': 'logo.svg',
    'logo_name': True,
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
html_sidebars = {
    '**': [
        'about.html',
        'navigation.html',
        'searchbox.html',
    ]
}

# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'kiwipydoc'

# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'kiwipy.tex', 'kiwipy Documentation', 'Martin Uhrin', 'manual'),
]

# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, 'kiwipy', 'kiwipy Documentation', [author], 1)]

# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc, 'kiwipy', 'kiwipy Documentation', author, 'kiwipy', 'One line description of project.',
        'Miscellaneous'
    ),
]

# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']

# -- Extension configuration -------------------------------------------------

# Warnings to ignore when using the -n (nitpicky) option
# We should ignore any python built-in exception, for instance
nitpick_ignore = []
for line in open('nitpick-exceptions'):
    if line.strip() == '' or line.startswith('#'):
        continue
    dtype, target = line.split(None, 1)
    target = target.strip()
    nitpick_ignore.append((dtype, target))

# API Documentation


def run_apidoc(app):
    """Runs sphinx-apidoc when building the documentation.

    Needs to be done in conf.py in order to include the APIdoc in the
    build on readthedocs.

    See also https://github.com/rtfd/readthedocs.org/issues/1139
    """
    from sphinx.ext.apidoc import main
    from sphinx.util import logging

    logger = logging.getLogger('apidoc')

    source_dir = Path(os.path.abspath(__file__)).parent
    apidoc_dir = source_dir / 'apidoc'
    apidoc_dir.mkdir(exist_ok=True)
    package_dir = source_dir.parent.parent / 'src' / 'kiwipy'

    # we write to a temporary folder first then only move across files that have changed
    # this ensures that document rebuilds are not triggered every time (due to change in file mtime)
    with tempfile.TemporaryDirectory() as tmpdirname:
        options = [
            '-o', tmpdirname,
            str(package_dir), '--private', '--force', '--module-first', '--separate', '--no-toc', '--maxdepth', '4',
            '-q'
        ]

        os.environ['SPHINX_APIDOC_OPTIONS'] = 'members,special-members,private-members,undoc-members,show-inheritance'
        main(options)

        for path in Path(tmpdirname).glob('*'):
            if not (apidoc_dir / path.name).exists() or not filecmp.cmp(path, apidoc_dir / path.name):
                logger.info(f'Writing: {apidoc_dir / path.name}')
                shutil.move(path, apidoc_dir / path.name)


autodoc_default_options = {
    # these all derive from concurrent.futures, whose docstrings are in the wrong format
    'exclude-members': 'CancelledError,wait,as_completed,Future,TimeoutError'
}


def setup(app):
    app.connect('builder-inited', run_apidoc)
