name: continuous-integration

on: [push, pull_request]

jobs:

    docs:

        runs-on: ubuntu-latest

        steps:
        -   uses: actions/checkout@v1

        -   name: Cache python dependencies
            id: cache-pip
            uses: actions/cache@v1
            with:
                path: ~/.cache/pip
                key: pip-docs-${{ hashFiles('**/setup.json') }}
                restore-keys:
                    pip-docs-

        -   name: Install system dependencies
            run: |
                sudo apt update
                sudo apt install pandoc

        -   name: Set up Python
            uses: actions/setup-python@v1
            with:
                python-version: 3.8

        -   name: Install python dependencies
            run:
                pip install -e .[rmq,dev,docs]

        -   name: Build documentation
            env:
                READTHEDOCS: 'True'
            run:
                SPHINXOPTS='-nW' make -C docs html

    tests:

        runs-on: ubuntu-latest

        strategy:
            matrix:
                python-version: [3.5, 3.6, 3.7, 3.8]

        services:
            rabbitmq:
                image: rabbitmq:latest
                ports:
                -   5672:5672

        steps:
        -   uses: actions/checkout@v2

        -   name: Cache python dependencies
            id: cache-pip
            uses: actions/cache@v1
            with:
                path: ~/.cache/pip
                key: pip-${{ matrix.python-version }}-tests-${{ hashFiles('**/setup.json') }}
                restore-keys:
                    pip-${{ matrix.python-version }}-tests

        -   name: Set up Python ${{ matrix.python-version }}
            uses: actions/setup-python@v1
            with:
                python-version: ${{ matrix.python-version }}

        -   name: Install python dependencies
            run:
                pip install -e .[dev,rmq]

        -   name: Run pytest
            run:
                pytest --cov=kiwipy -sv -p no:nb_regression test
